import { useState } from 'react';
import { SetBrowser } from '../components/SetBrowser';
import { MoveSetDialog } from '../components/MoveSetDialog';
import type { ProfileRecord, QuestionHistoryRecord, RunHistoryRecord, SetProgressRecord } from '../data/types';
import type { CuratedSetDefinition } from '../game';
import { formatDate, formatDuration, formatMoney } from '../utils/format';

interface CommonProps { playerName: string; onBack: () => void; }

export function StatisticsScreen({ profile, runs, questionHistory, playerName, onBack }: CommonProps & { profile: ProfileRecord | null; runs: readonly RunHistoryRecord[]; questionHistory: readonly QuestionHistoryRecord[] }) {
  const answered = runs.reduce((sum, run) => sum + run.correctCount + run.incorrectCount, 0);
  const correct = runs.reduce((sum, run) => sum + run.correctCount, 0);
  const averageReached = runs.length ? runs.reduce((sum, run) => sum + run.highestQuestion, 0) / runs.length : 0;
  const totalTime = runs.reduce((sum, run) => sum + run.durationMs, 0);
  const byLevel = Array.from({ length: 15 }, (_, index) => ({ level: index + 1, count: runs.filter((run) => run.highestQuestion >= index + 1).length }));
  return <main className="screen insights-screen" aria-labelledby="statistics-title"><InsightsHeader label="Your stats" title="Statistics" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="statistics-title">Your statistics</h1><p className="hero-subtitle">Your scores and progress across completed games.</p><div className="stat-grid"><Metric label="Personal best" value={formatMoney(profile?.statistics.highestPrize ?? Math.max(0, ...runs.map((run) => run.payout)))} accent /><Metric label="Million-dollar wins" value={String(profile?.statistics.millionaireWins ?? runs.filter((run) => run.outcome === 'millionaire').length)} /><Metric label="Games played" value={String(runs.length)} /><Metric label="Total winnings" value={formatMoney(profile?.statistics.totalVirtualWinnings ?? runs.reduce((sum, run) => sum + run.payout, 0))} /><Metric label="Answer accuracy" value={answered ? `${Math.round(correct / answered * 100)}%` : '—'} /><Metric label="Average question reached" value={runs.length ? averageReached.toFixed(1) : '—'} /><Metric label="Questions seen" value={String(questionHistory.length)} /><Metric label="Time played" value={formatDuration(totalTime)} /></div><section className="progress-panel panel"><div><span className="kicker">Questions reached</span><h2>How far you've reached</h2></div><div className="level-bars">{byLevel.map(({ level, count }) => <div key={level} title={`${count} run${count === 1 ? '' : 's'} reached Level ${level}`}><i style={{ height: `${runs.length ? Math.max(4, count / runs.length * 100) : 4}%` }} /><span>{level}</span></div>)}</div></section></div></main>;
}

export function HistoryScreen({ runs, sets, playerName, onBack, onSelect }: CommonProps & { runs: readonly RunHistoryRecord[]; sets: readonly CuratedSetDefinition[]; onSelect: (run: RunHistoryRecord) => void }) {
  return <main className="screen insights-screen" aria-labelledby="history-title"><InsightsHeader label="Your games" title="Past games" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="history-title">Past games</h1><p className="hero-subtitle">Choose a game to review your answers.</p>{runs.length ? <div className="history-table panel" role="table" aria-label="Completed runs"><div className="history-row history-row--header" role="row"><span>Date</span><span>Mode</span><span>Outcome</span><span>Reached</span><span>Payout</span><span /></div>{runs.map((run) => <button className="history-row" role="row" type="button" key={run.id} onClick={() => onSelect(run)}><span>{formatDate(run.completedAt)}</span><span>{run.mode === 'fresh-mix' ? 'Fresh Mix' : sets.find((set) => set.id === run.setId)?.title ?? 'Question set'}</span><span className={`outcome outcome--${run.outcome}`}>{run.outcome === 'millionaire' ? 'Millionaire' : run.outcome === 'walked-away' ? 'Walked away' : 'Incorrect'}</span><span>Q{run.highestQuestion}</span><strong>{formatMoney(run.payout)}</strong><span>Review →</span></button>)}</div> : <EmptyState title="No games played yet" copy="Finish a game to see your results here." />}</div></main>;
}

export function SetProgressScreen({ sets, progress, playerName, onBack, onPlay, onMove }: CommonProps & { sets: readonly CuratedSetDefinition[]; progress: readonly SetProgressRecord[]; onPlay: (setId: string) => void; onMove: (setId: string, folder: string[]) => Promise<void> }) {
  const byId = new Map(progress.map((entry) => [entry.setId, entry]));
  const [moving, setMoving] = useState<CuratedSetDefinition | null>(null);
  return <main className="screen insights-screen" aria-labelledby="sets-title"><InsightsHeader label="Question sets" title="Set library" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="sets-title">Set library</h1><p className="hero-subtitle">Browse by topic, find a set, or organize your own collection. Every set has 15 questions.</p><SetBrowser sets={sets} renderSet={(set) => { const item = byId.get(set.id); return <article className={`set-progress-card panel ${item?.wins ? 'set-progress-card--won' : ''}`} key={set.id}><span className="kicker">{set.theme || 'Mixed knowledge'}</span><h2>{set.title}</h2><p>{set.description}</p><dl><div><dt>Status</dt><dd>{item?.wins ? '$1,000,000 won' : item?.attempts ? 'Played' : 'New'}</dd></div><div><dt>Attempts</dt><dd>{item?.attempts ?? 0}</dd></div><div><dt>Best result</dt><dd>{formatMoney(item?.bestPrize ?? 0)} · Q{item?.bestQuestion ?? 0}</dd></div></dl><div className="set-library__actions"><button type="button" className="secondary-button" onClick={() => onPlay(set.id)}>{item?.attempts ? 'Play again' : 'Play set'}</button><button type="button" className="quiet-button" onClick={() => setMoving(set)} aria-label={`Move ${set.title}`}>Move</button></div></article>; }} />{moving && <MoveSetDialog set={moving} sets={sets} onMove={onMove} onClose={() => setMoving(null)} />}</div></main>;
}

function InsightsHeader({ label, title, onBack }: { label: string; title: string; onBack: () => void }) { return <header className="utility-bar"><div><div className="utility-label">{label}</div><div className="utility-value">{title}</div></div><div className="utility-bar__spacer" /><button className="quiet-button" type="button" onClick={onBack}>← Main menu</button></header>; }
function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`metric-card panel ${accent ? 'metric-card--accent' : ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="empty-state panel"><span>◇</span><h2>{title}</h2><p>{copy}</p></div>; }
